# Generated by Django 5.1.4 on 2024-12-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
